# Generated by Django 3.2.5 on 2023-12-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_zone', '0004_company_contact_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='contact_data',
        ),
    ]
